import React, { useState, useEffect } from 'react';
import styled from 'styled-components';
import { X, Printer, FileText, Activity, TrendingUp, AlertCircle } from 'lucide-react';
import axios from 'axios';

interface Props {
   isOpen: boolean;
   onClose: () => void;
   userId: string;
   userName: string;
   moodHistory: any[];
}

export const TherapistReportModal: React.FC<Props> = ({ isOpen, onClose, userId, userName, moodHistory }) => {
   const [clinicianNote, setClinicianNote] = useState<string>('');
   const [isLoading, setIsLoading] = useState(false);

   useEffect(() => {
      if (isOpen && userId) {
         const fetchNote = async () => {
            setIsLoading(true);
            try {
               const res = await axios.get(`http://localhost:8003/emotion/clinician-note/${userId}`);
               setClinicianNote(res.data.note);
            } catch (e) {
               console.error("Failed to fetch clinician note", e);
               setClinicianNote("Clinical summary unavailable at this time.");
            } finally {
               setIsLoading(false);
            }
         };
         fetchNote();
      }
   }, [isOpen, userId]);

   if (!isOpen) return null;

   const handlePrint = () => {
      window.print();
   };

   const dominantEmotion = moodHistory.length > 0
      ? Object.entries(moodHistory.reduce((acc, curr) => {
         Object.entries(curr.emotions || curr.aggregate_emotions || {}).forEach(([k, v]) => {
            acc[k] = (acc[k] || 0) + (v as number);
         });
         return acc;
      }, {} as any)).sort((a: any, b: any) => b[1] - a[1])[0][0]
      : 'No data';

   return (
      <Overlay>
         <ModalContainer id="printable-report">
            <Header>
               <div className="title-area">
                  <FileText size={24} color="#818cf8" />
                  <Title>Wellness Clinical Summary</Title>
               </div>
               <ActionButtons className="no-print">
                  <IconButton onClick={handlePrint}>
                     <Printer size={20} />
                  </IconButton>
                  <IconButton onClick={onClose}>
                     <X size={20} />
                  </IconButton>
               </ActionButtons>
            </Header>

            <ReportContent>
               <Section>
                  <SectionHeader>
                     <Activity size={18} /> Patient Information
                  </SectionHeader>
                  <InfoGrid>
                     <InfoItem>
                        <label>Name</label>
                        <span>{userName}</span>
                     </InfoItem>
                     <InfoItem>
                        <label>Report Date</label>
                        <span>{new Date().toLocaleDateString()}</span>
                     </InfoItem>
                     <InfoItem>
                        <label>Period Analyzed</label>
                        <span>Last 14 Days</span>
                     </InfoItem>
                  </InfoGrid>
               </Section>

               <Section>
                  <SectionHeader>
                     <TrendingUp size={18} /> Affective Assessment
                  </SectionHeader>
                  <p><strong>Primary Observed Affect:</strong> {dominantEmotion}</p>
                  <p className="description">
                     Based on the longitudinal data collected via Healix AI, the user has exhibited a baseline primarily consisting of {dominantEmotion.toLowerCase()}.
                  </p>
               </Section>

               <Section>
                  <SectionHeader>
                     <AlertCircle size={18} /> Clinician's AI Note
                  </SectionHeader>
                  {isLoading ? (
                     <LoadingText>Generating clinical analysis...</LoadingText>
                  ) : (
                     <NoteText>{clinicianNote}</NoteText>
                  )}
               </Section>

               <Footer>
                  <p>Generated by Healix AI Wellness Clinical Support System</p>
                  <p className="confidential">CONFIDENTIAL - FOR PROFESSIONAL USE ONLY</p>
               </Footer>
            </ReportContent>
         </ModalContainer>
      </Overlay>
   );
};

const Overlay = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.85);
  backdrop-filter: blur(10px);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 2000;
  padding: 20px;

  @media print {
    position: static;
    background: white;
    padding: 0;
  }
`;

const ModalContainer = styled.div`
  background: #f9fafb;
  width: 100%;
  max-width: 800px;
  max-height: 90vh;
  border-radius: 24px;
  border: 1px solid rgba(0, 0, 0, 0.08);
  display: flex;
  flex-direction: column;
  overflow: hidden;
  box-shadow: 0 30px 60px rgba(0,0,0,0.5);

  @media print {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    max-width: none;
    height: auto;
    max-height: none;
    background: white;
    color: black;
    border: none;
    box-shadow: none;
  }
`;

const Header = styled.div`
  padding: 24px 32px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.03);
  display: flex;
  align-items: center;
  justify-content: space-between;

  .title-area {
    display: flex;
    align-items: center;
    gap: 16px;
  }

  @media print {
    border-bottom: 2px solid #eee;
    .no-print { display: none; }
  }
`;

const Title = styled.h2`
  margin: 0;
  font-size: 1.5rem;
  font-weight: 700;
  color: #111827;

  @media print {
    color: black;
  }
`;

const ActionButtons = styled.div`
  display: flex;
  gap: 12px;
`;

const IconButton = styled.button`
  background: rgba(0, 0, 0, 0.03);
  border: 1px solid rgba(0, 0, 0, 0.08);
  color: #111827;
  width: 40px;
  height: 40px;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s;

  &:hover {
    background: rgba(0, 0, 0, 0.08);
  }
`;

const ReportContent = styled.div`
  padding: 40px;
  overflow-y: auto;
  flex: 1;

  @media print {
    overflow-y: visible;
    padding: 20px;
  }
`;

const Section = styled.div`
  margin-bottom: 40px;

  p {
    color: #374151;
    line-height: 1.6;
    margin: 12px 0;
  }

  .description {
    font-size: 0.95rem;
    color: #6b7280;
  }

  @media print {
    margin-bottom: 30px;
    p { color: black; }
    .description { color: #666; }
  }
`;

const SectionHeader = styled.h3`
  display: flex;
  align-items: center;
  gap: 10px;
  font-size: 1.1rem;
  font-weight: 600;
  color: #818cf8;
  margin-bottom: 20px;
  text-transform: uppercase;
  letter-spacing: 0.05em;

  @media print {
    color: #4f46e5;
    border-bottom: 1px solid #eee;
    padding-bottom: 8px;
  }
`;

const InfoGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 24px;
  background: rgba(0, 0, 0, 0.02);
  padding: 24px;
  border-radius: 16px;

  @media print {
    background: #f9f9f9;
    border: 1px solid #eee;
  }
`;

const InfoItem = styled.div`
  label {
    display: block;
    font-size: 0.75rem;
    color: #9ca3af;
    text-transform: uppercase;
    margin-bottom: 4px;
  }
  span {
    font-weight: 600;
    color: #111827;
  }

  @media print {
    label { color: #888; }
    span { color: black; }
  }
`;

const NoteText = styled.div`
  white-space: pre-wrap;
  background: rgba(0, 0, 0, 0.03);
  padding: 24px;
  border-radius: 16px;
  font-family: 'Inter', sans-serif;
  line-height: 1.8;
  color: #1f2937;

  @media print {
    background: transparent;
    padding: 0;
    color: black;
  }
`;

const LoadingText = styled.div`
  color: #818cf8;
  font-style: italic;
  text-align: center;
  padding: 40px;
`;

const Footer = styled.div`
  margin-top: 60px;
  border-top: 1px solid rgba(0, 0, 0, 0.03);
  padding-top: 24px;
  text-align: center;

  p {
    font-size: 0.85rem;
    color: #9ca3af;
    margin: 4px 0;
  }

  .confidential {
    font-weight: 700;
    letter-spacing: 0.2em;
    color: rgba(255, 77, 77, 0.4);
    margin-top: 12px;
  }

  @media print {
    border-top: 2px solid #eee;
    p { color: #888; }
    .confidential { color: #cc0000; }
  }
`;
